[phases.setup] 
aptPkgs = ["php8.3-bcmath", "php8.3-mysql", "php8.3-mbstring"] 
 
[phases.install] 
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-bcmath"] 
 
[providers] 
providers = ["php"]
